# Merging .csv files that we scraped.

Since we have a scraped a bunch of sepearted `.csv` files, it is not easy for us to perfom analysis on the seperated files. Therefore, it would be easier for us to use and analyze the data using a unified, one single `.csv` file. This documentation, would showcase how I performed the process.

At first, import the required libraries. We have set pd as an alias for the pandas library âˆ’

In [1]:
import pandas as pd
import glob
import os

## Locating the files

First, let's set the path for where the file is located.

In [2]:
# setting the path for joining multiple files
files = os.path.join("data/", "realdata*.csv")

Next, we would use `glob` to get all the file name that matches the pattern that we've keyed in.

In [4]:
# list of merged files returned
files = glob.glob(files)

In [5]:
files

['data/realdata9.csv',
 'data/realdata39.csv',
 'data/realdata11.csv',
 'data/realdata10.csv',
 'data/realdata38.csv',
 'data/realdata8.csv',
 'data/realdata12.csv',
 'data/realdata13.csv',
 'data/realdata17.csv',
 'data/realdata16.csv',
 'data/realdata14.csv',
 'data/realdata28.csv',
 'data/realdata29.csv',
 'data/realdata15.csv',
 'data/realdata40.csv',
 'data/realdata0.csv',
 'data/realdata18.csv',
 'data/realdata24.csv',
 'data/realdata30.csv',
 'data/realdata31.csv',
 'data/realdata25.csv',
 'data/realdata19.csv',
 'data/realdata1.csv',
 'data/realdata3.csv',
 'data/realdata33.csv',
 'data/realdata27.csv',
 'data/realdata26.csv',
 'data/realdata32.csv',
 'data/realdata2.csv',
 'data/realdata6.csv',
 'data/realdata36.csv',
 'data/realdata22.csv',
 'data/realdata23.csv',
 'data/realdata37.csv',
 'data/realdata7.csv',
 'data/realdata5.csv',
 'data/realdata21.csv',
 'data/realdata35.csv',
 'data/realdata34.csv',
 'data/realdata20.csv',
 'data/realdata4.csv']

In [7]:
len(files)

41

We could see there are 41 files.

## Combining files

Next, we will use pd to concat the `csv`s and output into one giant csv

In [11]:
# joining files with concat and read_csv
df_lst = []
for file in files:
    df = pd.read_csv(file, low_memory=False)
    df_lst.append(df)

In [12]:
return_df = pd.concat(df_lst, ignore_index=True)

In [13]:
return_df

,Unnamed: 0,index,term,course,Course,Instructor,Qtr/Yr,Enrollment,CAPEs Returned,Question,...,6,7,8,9,10,11,12,13,14,15
0,0,0.0,SP20,NANO 161,NANO 161 (A00) - Material Selection/Engineering,"Horvath, Stephen",SP20,16.0,7.0,General Info,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0.0,SP20,NANO 161,NaN,NaN,NaN,NaN,NaN,Your class level is,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.0,SP20,NANO 161,NaN,NaN,NaN,NaN,NaN,Your reason for taking this class is,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,0.0,SP20,NANO 161,NaN,NaN,NaN,NaN,NaN,What grade do you expect in this class?,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0.0,SP20,NANO 161,NaN,NaN,NaN,NaN,NaN,I learned a great deal from this course.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2027426,23,0.0,WI21,CHEM 40B,NaN,NaN,NaN,NaN,NaN,Instructor is effective in promoting academic ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2027427,24,0.0,WI21,CHEM 40B,NaN,NaN,NaN,NaN,NaN,The instructor practiced effective teaching st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2027428,25,0.0,WI21,CHEM 40B,NaN,NaN,NaN,NaN,NaN,Do you recommend this professor overall?,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2027429,0,NaN,WI21,CHEM 40B,NaN,NaN,NaN,NaN,NaN,Grade received,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2027430,1,NaN,WI21,CHEM 40B,NaN,NaN,NaN,NaN,NaN,Grade received,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Outputing the file

In [14]:
return_df.to_csv("data/realdata_merge.csv")

That's it! Congrats! Now, you've successfully combined and output the csv.